defmodule LocalFirst.Repo.Migrations.CreateReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reports, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_mutation_id, :uuid
      add :version, :bigint, null: false
      add :deleted, :boolean, null: false
      add :status, :text, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :description, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:reports)
  end
end
