defmodule LocalFirstWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :local_first
  plug :put_wasm_security_headers
  plug LocalFirstWeb.MobileCors

  defp put_wasm_security_headers(conn, _opts) do
    conn
    |> put_resp_header("cross-origin-opener-policy", "same-origin")
    |> put_resp_header("cross-origin-embedder-policy", "require-corp")
  end

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_local_first_key",
    signing_salt: "pc9YX5kv",
    same_site: "Lax"
  ]

  socket "/llv_socket", LocalLiveView.Socket,
    websocket: [connect_info: [session: @session_options]]

  socket "/reports_socket", LocalFirstWeb.ReportsSocket,
    websocket: [check_origin: {__MODULE__, :reports_origin?, []}],
    longpoll: false

  def reports_origin?(%URI{} = origin) do
    configured = URI.parse(url())

    {origin.scheme, origin.host, origin.port} in [
      {"https", "localhost", 443},
      {configured.scheme, configured.host, configured.port}
    ]
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :local_first,
    gzip: not code_reloading?,
    only: LocalFirstWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :local_first
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LocalFirstWeb.Router
end
